// SPDX-License-Identifier: MIT
// Copyright (c) 2026 OgonFrameworks. All rights reserved.
//
// a11y test gen (TEST-033) and visual smoke (TEST-034). Both are optional
// because they require external tooling (axe-core / Playwright). The
// fixtures generate the spec files; CI runs them with the appropriate
// runtime.

package test

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// A11yConfig captures the inputs to the generated axe-core spec.
type A11yConfig struct {
	OutputDir string   // directory to write spec into
	BaseURL   string   // app root URL
	Pages     []string // list of pages to scan
	Tags      []string // axe tags, e.g., ["wcag2a","wcag2aa"]; default both
}

// Emit writes tests/a11y.spec.ts that uses @axe-core/playwright to scan
// every declared page for violations. Returns the absolute path.
func (c *A11yConfig) Emit() (string, error) {
	if c.OutputDir == "" {
		return "", fmt.Errorf("ogontest: A11yConfig.OutputDir required")
	}
	if c.BaseURL == "" {
		c.BaseURL = "http://localhost:3000"
	}
	if len(c.Tags) == 0 {
		c.Tags = []string{"wcag2a", "wcag2aa"}
	}
	dir := filepath.Join(c.OutputDir, "tests")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	pages := append([]string(nil), c.Pages...)
	sort.Strings(pages)
	var b strings.Builder
	b.WriteString("import { test, expect } from '@playwright/test';\n")
	b.WriteString("import AxeBuilder from '@axe-core/playwright';\n\n")
	b.WriteString("// Auto-generated by ogontest.A11yConfig (TEST-033).\n\n")
	for _, page := range pages {
		label := routeLabel(page)
		fmt.Fprintf(&b, "test('a11y: %s has no critical violations', async ({ page }) => {\n", label)
		fmt.Fprintf(&b, "  await page.goto('%s%s');\n", c.BaseURL, page)
		fmt.Fprintf(&b, "  const results = await new AxeBuilder({ page }).withTags(%#v).analyze();\n", c.Tags)
		b.WriteString("  expect(results.violations.filter(v => v.impact === 'critical')).toEqual([]);\n")
		b.WriteString("});\n\n")
	}
	path := filepath.Join(dir, "a11y.spec.ts")
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

// VisualSmokeConfig captures the inputs to the generated visual-smoke spec.
type VisualSmokeConfig struct {
	OutputDir string
	BaseURL   string
	Pages     []string
}

// Emit writes tests/visual-smoke.spec.ts that takes a screenshot of each
// page and asserts the screenshot matches the stored baseline. Returns
// the absolute path.
func (c *VisualSmokeConfig) Emit() (string, error) {
	if c.OutputDir == "" {
		return "", fmt.Errorf("ogontest: VisualSmokeConfig.OutputDir required")
	}
	if c.BaseURL == "" {
		c.BaseURL = "http://localhost:3000"
	}
	dir := filepath.Join(c.OutputDir, "tests")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	pages := append([]string(nil), c.Pages...)
	sort.Strings(pages)
	var b strings.Builder
	b.WriteString("import { test, expect } from '@playwright/test';\n\n")
	b.WriteString("// Auto-generated by ogontest.VisualSmokeConfig (TEST-034).\n")
	b.WriteString("// Screenshots stored under tests/__screenshots__/.\n\n")
	for _, page := range pages {
		label := routeLabel(page)
		fmt.Fprintf(&b, "test('visual: %s matches baseline', async ({ page }) => {\n", label)
		fmt.Fprintf(&b, "  await page.goto('%s%s');\n", c.BaseURL, page)
		fmt.Fprintf(&b, "  await expect(page).toHaveScreenshot('%s.png');\n", label)
		b.WriteString("});\n\n")
	}
	path := filepath.Join(dir, "visual-smoke.spec.ts")
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return "", err
	}
	return path, nil
}
