// SPDX-License-Identifier: MIT
// Copyright (c) 2026 OgonFrameworks. All rights reserved.
//
// CI template (TEST-017/018/019/051/040). Produces a GitHub Actions workflow
// and a pre-commit hook file from a single source of truth so the test
// guarantees are codified in exactly one place. The output is plain text;
// tests in this package assert it parses the way CI expects.

package test

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// CIConfig captures the inputs to the generated CI artefacts.
type CIConfig struct {
	OutputDir      string   // directory to write into
	GoVersion      string   // e.g., "1.27"
	CoverageGate   float64  // e.g., 85 → fail if total < 85%
	Race           bool     // enable -race (TEST-018)
	FuzzSeeds      []string // list of registered fuzz targets to run (TEST-019)
	BudgetGate     bool     // enable PERF budget regression gate (TEST-051)
	PreCommit      bool     // emit .pre-commit-hooks.yaml (TEST-040)
	Concurrency    int      // CI concurrency for matrix; 0 → 1
	TimeoutMinutes int      // job-level timeout
}

// Emit writes .github/workflows/ogon-ci.yml and .pre-commit-hooks.yaml (if
// enabled). Returns the absolute paths written.
func (c *CIConfig) Emit() ([]string, error) {
	if c.OutputDir == "" {
		return nil, fmt.Errorf("ogontest: CIConfig.OutputDir required")
	}
	if c.GoVersion == "" {
		c.GoVersion = "1.27"
	}
	if c.TimeoutMinutes == 0 {
		c.TimeoutMinutes = 15
	}
	if c.Concurrency == 0 {
		c.Concurrency = 1
	}
	ghDir := filepath.Join(c.OutputDir, ".github", "workflows")
	if err := os.MkdirAll(ghDir, 0o755); err != nil {
		return nil, err
	}
	wfPath := filepath.Join(ghDir, "ogon-ci.yml")
	if err := os.WriteFile(wfPath, []byte(c.workflow()), 0o644); err != nil {
		return nil, err
	}
	paths := []string{wfPath}
	if c.PreCommit {
		pcPath := filepath.Join(c.OutputDir, ".pre-commit-hooks.yaml")
		if err := os.WriteFile(pcPath, []byte(c.preCommitHooks()), 0o644); err != nil {
			return nil, err
		}
		paths = append(paths, pcPath)
	}
	return paths, nil
}

func (c *CIConfig) workflow() string {
	var b strings.Builder
	fmt.Fprintf(&b, "name: ogon-ci\n")
	fmt.Fprintf(&b, "on:\n  push:\n    branches: [main]\n  pull_request:\n")
	fmt.Fprintf(&b, "permissions:\n  contents: read\n")
	fmt.Fprintf(&b, "concurrency:\n  group: ${{ github.workflow }}-${{ github.ref }}\n  cancel-in-progress: true\n\n")
	fmt.Fprintf(&b, "jobs:\n  test:\n    runs-on: ubuntu-latest\n    timeout-minutes: %d\n", c.TimeoutMinutes)
	fmt.Fprintf(&b, "    steps:\n")
	fmt.Fprintf(&b, "      - uses: actions/checkout@v4\n")
	fmt.Fprintf(&b, "      - uses: actions/setup-go@v5\n        with:\n          go-version: %q\n", c.GoVersion)
	fmt.Fprintf(&b, "      - run: go mod download\n")
	fmt.Fprintf(&b, "      - name: vet\n        run: go vet ./...\n")
	fmt.Fprintf(&b, "      - name: fmt-check\n        run: test -z \"$(gofmt -l .)\"\n")
	fmt.Fprintf(&b, "      - name: build\n        run: go build ./...\n")
	raceFlag := ""
	if c.Race {
		raceFlag = "-race"
		fmt.Fprintf(&b, "      - name: test (race)\n        run: go test %s -count=1 ./...\n", raceFlag)
	} else {
		fmt.Fprintf(&b, "      - name: test\n        run: go test -count=1 ./...\n")
	}
	if c.CoverageGate > 0 {
		fmt.Fprintf(&b, "      - name: coverage\n        run: |\n")
		fmt.Fprintf(&b, "          go test -coverprofile=cover.out ./...\n")
		fmt.Fprintf(&b, "          go tool cover -func=cover.out | tee cover.txt\n")
		fmt.Fprintf(&b, "          COV=$(awk '/^total:/ {print substr($3,1,length($3)-1)}' cover.txt)\n")
		fmt.Fprintf(&b, "          awk 'BEGIN {exit !(%v <= %s)}' || { echo \"coverage %s%% < %v%%\"; exit 1; }\n",
			c.CoverageGate, "$COV", "$COV", c.CoverageGate)
	}
	for _, f := range c.FuzzSeeds {
		fmt.Fprintf(&b, "      - name: fuzz %s\n        run: go test -run=^$ -fuzz=Fuzz%s -fuzztime=30s ./...\n", f, f)
	}
	if c.BudgetGate {
		fmt.Fprintf(&b, "      - name: budget-gate\n        run: ogon benchmark perf --gate ./benchmarks/last.json\n")
	}
	fmt.Fprintf(&b, "      - name: ogon check\n        run: ogon check\n")
	return b.String()
}

func (c *CIConfig) preCommitHooks() string {
	var b strings.Builder
	b.WriteString("# Auto-generated by ogontest.CIConfig (TEST-040). Pre-commit hooks.\n")
	b.WriteString("- id: ogon-fmt\n  name: ogon fmt\n  entry: ogon fmt\n  language: system\n  files: '\\.go$'\n")
	b.WriteString("- id: ogon-lint\n  name: ogon lint\n  entry: ogon lint\n  language: system\n  files: '\\.go$'\n")
	b.WriteString("- id: ogon-check\n  name: ogon check\n  entry: ogon check\n  language: system\n  pass_filenames: false\n")
	return b.String()
}
