// SPDX-License-Identifier: MIT
// Copyright (c) 2026 OgonFrameworks. All rights reserved.
//
// Load-test script gen (TEST-023). Emits either a k6 or vegeta script for
// the supplied workload description. The fixture does not run the script;
// the CI pipeline runs `k6 run` or `vegeta attack` separately.

package test

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// LoadWorkload describes a single load-test scenario.
type LoadWorkload struct {
	Name      string
	BaseURL   string            // e.g., http://localhost:8080
	Route     string            // e.g., /api/users
	Method    string            // default GET
	RPS       int               // target rate; default 100
	Duration  string            // e.g., "30s"
	Headers   map[string]string // optional headers (auth, etc.)
	Body      string            // optional JSON body for non-GET
	OutputDir string            // directory to write script into
	Tool      string            // "k6" (default) or "vegeta"
}

// Emit writes the script file to OutputDir. Returns the absolute path.
func (w *LoadWorkload) Emit() (string, error) {
	if w.OutputDir == "" {
		return "", fmt.Errorf("ogontest: LoadWorkload.OutputDir required")
	}
	if w.BaseURL == "" {
		w.BaseURL = "http://localhost:8080"
	}
	if w.Method == "" {
		w.Method = "GET"
	}
	if w.RPS == 0 {
		w.RPS = 100
	}
	if w.Duration == "" {
		w.Duration = "30s"
	}
	if w.Tool == "" {
		w.Tool = "k6"
	}
	if err := os.MkdirAll(w.OutputDir, 0o755); err != nil {
		return "", err
	}
	var (
		path    string
		content string
	)
	switch strings.ToLower(w.Tool) {
	case "k6":
		path = filepath.Join(w.OutputDir, w.Name+".k6.js")
		content = w.k6Script()
	case "vegeta":
		path = filepath.Join(w.OutputDir, w.Name+".vegeta.go")
		content = w.vegetaScript()
	default:
		return "", fmt.Errorf("ogontest: unknown load tool %q", w.Tool)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

func (w *LoadWorkload) k6Script() string {
	var b strings.Builder
	b.WriteString("// Auto-generated by ogontest.LoadWorkload (TEST-023).\n")
	b.WriteString("import http from 'k6/http';\n")
	b.WriteString("import { check, sleep } from 'k6';\n\n")
	fmt.Fprintf(&b, "export const options = {\n")
	fmt.Fprintf(&b, "  stages: [\n    { duration: %q, target: %d },\n  ],\n", w.Duration, w.RPS)
	b.WriteString("};\n\n")
	b.WriteString("export default function () {\n")
	var headers []string
	for k, v := range w.Headers {
		headers = append(headers, fmt.Sprintf("'%s': '%s'", k, v))
	}
	hdr := "{}"
	if len(headers) > 0 {
		hdr = "{" + strings.Join(headers, ", ") + "}"
	}
	if w.Body != "" {
		fmt.Fprintf(&b, "  const res = http.request(%q, `%s/%s`, `%s`, { headers: %s });\n",
			w.Method, w.BaseURL, w.Route, w.Body, hdr)
	} else {
		fmt.Fprintf(&b, "  const res = http.request(%q, `%s%s`, null, { headers: %s });\n",
			w.Method, w.BaseURL, w.Route, hdr)
	}
	fmt.Fprintf(&b, "  check(res, { 'status 200': (r) => r.status === 200 });\n")
	b.WriteString("}\n")
	return b.String()
}

func (w *LoadWorkload) vegetaScript() string {
	var b strings.Builder
	b.WriteString("// Auto-generated by ogontest.LoadWorkload (TEST-023).\n")
	b.WriteString("package main\n\n")
	b.WriteString("import (\n  \"fmt\"\n  \"time\"\n  \"github.com/negrel/vegeta\"\n)\n\n")
	b.WriteString("func main() {\n")
	fmt.Fprintf(&b, "  rate := %d\n", w.RPS)
	fmt.Fprintf(&b, "  dur, _ := time.ParseDuration(%q)\n", w.Duration)
	fmt.Fprintf(&b, "  target := %q\n", w.BaseURL+w.Route)
	b.WriteString("  attacker := vegeta.NewAttacker()\n")
	b.WriteString("  results := attacker.Attack(\n    vegeta.NewStaticTargeter(vegeta.Target{\n")
	fmt.Fprintf(&b, "      Method: %q, URL: target,\n", strings.ToUpper(w.Method))
	if w.Body != "" {
		fmt.Fprintf(&b, "      Body: []byte(%q),\n", w.Body)
	}
	b.WriteString("    }), rate, dur, \"ogon-load\")\n")
	b.WriteString("  for res := range results {\n    fmt.Println(res)\n  }\n")
	b.WriteString("}\n")
	return b.String()
}
