// SPDX-License-Identifier: MIT
// Copyright (c) 2026 OgonFrameworks. All rights reserved.
//
// Mutation-testing doc (TEST-041, optional), property-test examples
// (TEST-042), and time-dependent testing guide (TEST-043). These are doc
// templates + small helpers; they do not run a mutation engine. The
// assumption is that the project will use `gremlins` or equivalent, and
// the doc explains how to interpret the output.

package test

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// MutationGuide is the markdown content for TEST-041.
const MutationGuide = `# Mutation testing guide (TEST-041)

## What it is

Mutation testing rewrites the production code in small ways ("mutants") and
checks whether the test suite catches the change. A surviving mutant is a
hole in coverage: code that the tests do not actually exercise meaningfully.

## How to run

	ogon test mutation --base main --diff HEAD

The command wraps ` + "`gremlins go`" + ` (or the engine configured in
` + "`ogon.yaml -> testing -> mutation_engine`" + `) and emits a JSON report
under testdata/mutation/.

## Interpreting results

A mutant survival rate above 5% indicates one of three problems:

  1. The test for that line is missing or asserts nothing meaningful.
  2. The line is defensive code that should not exist (delete the line).
  3. The mutant is equivalent (the engine cannot tell that two expressions
     produce the same output for all inputs). Equivalent mutants are
     unfixable; flag them in the report so future runs ignore them.

## What NOT to do

Do not write tests just to kill mutants. Tests exist to document behaviour
and catch regressions. A mutant that survives because the tests check the
right thing is fine; that mutant is equivalent.

## The law

The test infrastructure law from Part XIV applies: writing mutation tests
must not exceed the behaviour under test. If a mutant survives, fix the
production code or delete it. Never add a test whose only purpose is to
kill a mutant.
`

// PropertyTestExample demonstrates one quickcheck-style property: a counter
// increment is monotonic. The point is the pattern, not the property.
type PropertyTestExample struct {
	Name string
	Run  func(seed int64) error
}

// MutationConfig captures the inputs to a mutation-test config.
type MutationConfig struct {
	OutputDir string
	Base      string
	Engine    string
}

// Emit writes testdata/mutation/guide.md and ogon.mutation.yaml (TEST-041).
func (c *MutationConfig) Emit() ([]string, error) {
	if c.OutputDir == "" {
		return nil, fmt.Errorf("ogontest: MutationConfig.OutputDir required")
	}
	if c.Engine == "" {
		c.Engine = "gremlins"
	}
	if c.Base == "" {
		c.Base = "main"
	}
	dir := filepath.Join(c.OutputDir, "testdata", "mutation")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, err
	}
	guidePath := filepath.Join(dir, "guide.md")
	if err := os.WriteFile(guidePath, []byte(MutationGuide), 0o644); err != nil {
		return nil, err
	}
	cfgPath := filepath.Join(c.OutputDir, "ogon.mutation.yaml")
	if err := os.WriteFile(cfgPath, []byte(c.yaml()), 0o644); err != nil {
		return nil, err
	}
	return []string{guidePath, cfgPath}, nil
}

func (c *MutationConfig) yaml() string {
	var b strings.Builder
	b.WriteString("# Auto-generated by ogontest.MutationConfig (TEST-041).\n")
	b.WriteString("testing:\n")
	fmt.Fprintf(&b, "  mutation_engine: %q\n", c.Engine)
	fmt.Fprintf(&b, "  base: %q\n", c.Base)
	b.WriteString("  output: testdata/mutation/report.json\n")
	b.WriteString("  thresholds:\n")
	b.WriteString("    survival_rate_max: 0.05\n")
	return b.String()
}

// TimeDependentGuide is the markdown content for TEST-043.
const TimeDependentGuide = `# Time-dependent testing guide (TEST-043)

## Use the FakeClock

Never call time.Now in production code. Inject a Clock interface and pass
ogontest.FakeClock in tests. The fixture is monotonic; Advance moves the
clock forward deterministically. After/AfterFunc fire when the clock passes
the deadline.

	clk := ogontest.NewFakeClock(time.Now().UnixNano())
	codeUnderTest.Run(clk)
	clk.Advance(2 * time.Second)
	ogontest.AssertTrue(t, fired)

## Time zones

Always store and compare UTC. Tests that need to assert local-time display
should set TZ=UTC in t.Cleanup so the test is reproducible regardless of
host timezone.

	ogontest.WithEnv(t, "TZ", "UTC")

## Wall-clock in tests

Avoid time.Sleep in tests. Prefer:
  - clk.Advance(d) for in-process clocks
  - assert.Eventually / require.Eventually when waiting on a goroutine
  - ogontest.WaitFor(ctx, n) for live/SSE consumers

## Determinism

Seed random sources from ogontest.FakerSeed(t). This makes flake rate zero
on tests that use random data: every test with the same name sees the same
sequence.
`

// PropertyTestExamples returns a slice of example property tests. The
// caller wires them into a fuzz harness or a quickcheck harness. The
// examples exist primarily to document the pattern (TEST-042).
func PropertyTestExamples() []PropertyTestExample {
	return []PropertyTestExample{
		{
			Name: "counter_monotonic",
			Run: func(seed int64) error {
				// counter monotonic property: increment never decreases.
				// Pseudo-implementation; tests are expected to replace Run.
				if seed < 0 {
					return errStr("seed must be non-negative")
				}
				return nil
			},
		},
		{
			Name: "clock_advances_forward",
			Run: func(seed int64) error {
				c := NewFakeClock(seed)
				before := c.CurrentNanos()
				c.Advance(time.Second)
				after := c.CurrentNanos()
				if after <= before {
					return errStr("clock did not advance forward")
				}
				return nil
			},
		},
	}
}
