// SPDX-License-Identifier: MIT
// Copyright (c) 2026 OgonFrameworks. All rights reserved.
//
// Playwright config gen (TEST-016, UI-057). Emits a minimal Playwright
// config + a smoke-test spec that exercises every declared data-testid.
// The fixture does not run Playwright; it produces the files. CI runs
// `npx playwright test` separately.

package test

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// PlaywrightConfig captures the inputs to the generated config.
type PlaywrightConfig struct {
	BaseURL        string   // e.g., http://localhost:3000
	TestIDs        []string // list of data-testid values to assert exist
	OutputDir      string   // where to write the config + spec
	Headless       bool
	Browsers       []string // default: ["chromium"]
	ScreenshotMode string   // "only-on-failure" (default), "always", "off"
}

// Emit writes playwright.config.ts and tests/ogontest.spec.ts to OutputDir.
// Returns the absolute paths written.
func (c *PlaywrightConfig) Emit() ([]string, error) {
	if c.OutputDir == "" {
		return nil, fmt.Errorf("ogontest: PlaywrightConfig.OutputDir required")
	}
	if c.BaseURL == "" {
		c.BaseURL = "http://localhost:3000"
	}
	if len(c.Browsers) == 0 {
		c.Browsers = []string{"chromium"}
	}
	if c.ScreenshotMode == "" {
		c.ScreenshotMode = "only-on-failure"
	}
	if err := os.MkdirAll(c.OutputDir, 0o755); err != nil {
		return nil, err
	}
	if err := os.MkdirAll(filepath.Join(c.OutputDir, "tests"), 0o755); err != nil {
		return nil, err
	}
	cfgPath := filepath.Join(c.OutputDir, "playwright.config.ts")
	if err := os.WriteFile(cfgPath, []byte(c.configTS()), 0o644); err != nil {
		return nil, err
	}
	specPath := filepath.Join(c.OutputDir, "tests", "ogontest.spec.ts")
	if err := os.WriteFile(specPath, []byte(c.specTS()), 0o644); err != nil {
		return nil, err
	}
	return []string{cfgPath, specPath}, nil
}

func (c *PlaywrightConfig) configTS() string {
	browsers := make([]string, 0, len(c.Browsers))
	for _, b := range c.Browsers {
		browsers = append(browsers, fmt.Sprintf("  { name: %q, use: { ...devices[%q] } },", b, titleCase(b)))
	}
	return fmt.Sprintf(`import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: process.env.CI ? 'github' : 'list',
  use: {
    baseURL: %q,
    trace: 'on-first-retry',
    screenshot: %q,
    headless: %t,
  },
  projects: [
%s
  ],
});
`, c.BaseURL, c.ScreenshotMode, c.Headless, strings.Join(browsers, "\n"))
}

func (c *PlaywrightConfig) specTS() string {
	ids := append([]string(nil), c.TestIDs...)
	sort.Strings(ids)
	var b strings.Builder
	b.WriteString("import { test, expect } from '@playwright/test';\n\n")
	b.WriteString("// Auto-generated by ogontest.PlaywrightConfig (TEST-016, UI-057).\n")
	b.WriteString("// Re-run `ogon gen test playwright` after adding data-testid.\n\n")
	b.WriteString("test('smoke: every declared data-testid is reachable', async ({ page }) => {\n")
	b.WriteString("  await page.goto('/');\n")
	for _, id := range ids {
		fmt.Fprintf(&b, "  await expect(page.getByTestId(%q)).toBeVisible({ timeout: 10_000 });\n", id)
	}
	b.WriteString("});\n")
	return b.String()
}

func titleCase(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
