// SPDX-License-Identifier: MIT
// Copyright (c) 2026 OgonFrameworks. All rights reserved.
//
// `<go>` block → Go handler generator (UI-001/002). The generated
// Go file contains:
//   - The component struct with Props/State fields.
//   - Typed event-dispatch methods (Mount/Unmount/Handle<Event>).
//   - The wire-handler glue that turns WS payloads into typed
//     method invocations (UI-008).
//
// The output is gofmt-clean and passes `go vet` once the runtime
// imports are wired by the project's go.mod.

package compiler

import (
	"fmt"
	"strings"
)

// GoCodegen emits the Go side of a `.ogon` component.
type GoCodegen struct {
	file *File
}

// NewGoCodegen constructs the codegen for a parsed `.ogon` file.
func NewGoCodegen(f *File) *GoCodegen { return &GoCodegen{file: f} }

// Emit returns the generated Go source text for the `<go>` block.
func (g *GoCodegen) Emit() string {
	var b strings.Builder
	pkg := "components"
	if g.file.Go != nil && g.file.Go.Package != "" {
		pkg = g.file.Go.Package
	}
	b.WriteString("// Code generated by ogon/ui. DO NOT EDIT.\n")
	b.WriteString("// SPDX-License-Identifier: MIT\n")
	b.WriteString("// Component: " + g.file.Name + "\n\n")
	b.WriteString("package " + pkg + "\n\n")

	// Imports.
	b.WriteString("import (\n")
	for _, imp := range g.collectImports() {
		fmt.Fprintf(&b, "\t%q\n", imp)
	}
	b.WriteString(")\n\n")

	// Struct declaration.
	b.WriteString("// " + g.file.Name + " is a live UI component generated from " +
		g.file.Name + ".ogon (UI-001/002/008).\n")
	b.WriteString("type " + g.file.Name + " struct {\n")
	if g.file.Go != nil {
		for _, p := range g.file.Go.Props {
			fmt.Fprintf(&b, "\t%s %s\n", p.Name, p.Type)
		}
		for _, s := range g.file.Go.State {
			fmt.Fprintf(&b, "\t%s %s\n", s.Name, s.Type)
		}
	}
	b.WriteString("}\n\n")

	// Mount/Unmount/Handle<Event> methods (copied from <go> block).
	if g.file.Go != nil {
		for _, m := range g.file.Go.Mounts {
			b.WriteString(m.Body)
			b.WriteString("\n\n")
		}
		for _, m := range g.file.Go.Unmounts {
			b.WriteString(m.Body)
			b.WriteString("\n\n")
		}
		for _, m := range g.file.Go.Methods {
			b.WriteString(m.Body)
			b.WriteString("\n\n")
		}
	}

	// Wire handler — dispatches WS events to typed methods (UI-008).
	g.emitWireHandler(&b)

	return b.String()
}

// emitWireHandler writes a single HandleEvent method that routes
// incoming wire payloads to typed component methods. The dispatch
// table is generated from the directives observed in <template>.
func (g *GoCodegen) emitWireHandler(b *strings.Builder) {
	b.WriteString("// HandleEvent dispatches a live-protocol event payload\n")
	b.WriteString("// to a typed component handler (UI-008).\n")
	b.WriteString("func (c *" + g.file.Name + ") HandleEvent(name string, payload map[string]any) error {\n")
	b.WriteString("\tswitch name {\n")
	handlers := g.collectHandlers()
	for _, h := range handlers {
		fmt.Fprintf(b, "\tcase %q:\n", h)
		fmt.Fprintf(b, "\t\treturn c.%s(payload)\n", h)
	}
	b.WriteString("\tdefault:\n")
	b.WriteString("\t\treturn fmt.Errorf(\"ogon/ui: unknown handler %%q\", name)\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")
}

// collectImports returns the Go import path set. Always includes
// "fmt" because HandleEvent uses it.
func (g *GoCodegen) collectImports() []string {
	imps := []string{"fmt"}
	if g.file.Go != nil {
		imps = append(imps, g.file.Go.Imports...)
	}
	return uniqueStrings(imps)
}

// collectHandlers returns the unique set of handler method names
// referenced by ogon:click / ogon:submit directives.
func (g *GoCodegen) collectHandlers() []string {
	out := []string{}
	visitElements(g.file.Root, func(el *Element) {
		for _, d := range el.Directives {
			if d.Binding != nil && d.Binding.Handler != "" {
				out = append(out, d.Binding.Handler)
			}
		}
	})
	return uniqueStrings(out)
}

// visitElements walks the element tree, calling fn for each element.
func visitElements(root *Element, fn func(*Element)) {
	if root == nil {
		return
	}
	fn(root)
	for _, child := range root.Children {
		if el, ok := child.(*Element); ok {
			visitElements(el, fn)
		}
	}
}

func uniqueStrings(in []string) []string {
	seen := map[string]bool{}
	out := []string{}
	for _, s := range in {
		if !seen[s] {
			seen[s] = true
			out = append(out, s)
		}
	}
	return out
}
