// SPDX-License-Identifier: MIT
// Copyright (c) 2026 OgonFrameworks. All rights reserved.
//
// `<template>` → typed Go render function (UI-003/091). The
// generator splits the template into reactive regions keyed by the
// primitives each region reads, then emits one Go render function
// per region. Region functions are pure: they read State/Derived
// values and return a string fragment. A top-level Render(...) walks
// the region tree and concatenates outputs.

package compiler

import (
	"fmt"
	"strings"
)

// TemplateCodegen emits the typed Go render function.
type TemplateCodegen struct {
	file *File
}

// NewTemplateCodegen constructs the codegen.
func NewTemplateCodegen(f *File) *TemplateCodegen { return &TemplateCodegen{file: f} }

// Emit returns the generated Go source text for the template.
func (g *TemplateCodegen) Emit() string {
	var b strings.Builder
	b.WriteString("// Code generated by ogon/ui. DO NOT EDIT.\n")
	b.WriteString("// Template render functions (UI-003/091).\n\n")
	b.WriteString("package " + g.file.PkgName + "\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"bytes\"\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString(")\n\n")

	// Top-level Render entry point.
	b.WriteString("// Render writes the rendered template to the supplied buffer.\n")
	b.WriteString("// Reactive regions are listed in dependency order; the runtime\n")
	b.WriteString("// patcher re-runs only invalidated regions (UI-091).\n")
	b.WriteString("func (c *" + g.file.Name + ") Render() string {\n")
	b.WriteString("\tvar b bytes.Buffer\n")
	g.emitRegion(&b, g.file.Root, "root")
	b.WriteString("\treturn b.String()\n")
	b.WriteString("}\n\n")

	return b.String()
}

// emitRegion walks an element and emits Go statements that write
// the rendered output to the buffer. Reactive regions are named
// `region_<idx>` so the patcher can target them.
func (g *TemplateCodegen) emitRegion(b *strings.Builder, n Node, region string) {
	if n == nil {
		return
	}
	switch t := n.(type) {
	case *Element:
		g.emitElement(b, t, region)
	case *Interp:
		fmt.Fprintf(b, "\tfmt.Fprintf(&b, \"%%v\", c.eval_%s())\n", sanitizeIdent(t.Expr))
	}
}

func (g *TemplateCodegen) emitElement(b *strings.Builder, el *Element, region string) {
	if el.Tag == "" {
		// Text-only element.
		b.WriteString("\tb.WriteString(")
		b.WriteString(quoteGoString(el.Text))
		b.WriteString(")\n")
		return
	}
	fmt.Fprintf(b, "\tb.WriteString(\"<%s\")\n", el.Tag)
	for _, attr := range el.Order {
		val := el.Attrs[attr]
		fmt.Fprintf(b, "\tb.WriteString(\" %s=\\\"\")\n", attr)
		fmt.Fprintf(b, "\tb.WriteString(%s)\n", quoteGoString(val))
		b.WriteString("\tb.WriteString(\"\\\"\")\n")
	}
	for _, d := range el.Directives {
		g.emitDirective(b, d)
	}
	if el.SelfClose || isVoid(el.Tag) {
		fmt.Fprintf(b, "\tb.WriteString(\"/>\")\n")
		return
	}
	fmt.Fprintf(b, "\tb.WriteString(\">\")\n")
	if el.Text != "" {
		fmt.Fprintf(b, "\tb.WriteString(%s)\n", quoteGoString(el.Text))
	}
	for i, child := range el.Children {
		g.emitRegion(b, child, fmt.Sprintf("%s_%d", region, i))
	}
	fmt.Fprintf(b, "\tb.WriteString(\"</%s>\")\n", el.Tag)
}

func (g *TemplateCodegen) emitDirective(b *strings.Builder, d *Directive) {
	switch d.Name {
	case "model":
		// Wire ogon:model into the component's two-way binding helper.
		fmt.Fprintf(b, "\t// ogon:model binds to %s\n", d.Binding.State)
	case "click":
		fmt.Fprintf(b, "\t// ogon:click dispatches to %s\n", d.Binding.Handler)
	case "if":
		fmt.Fprintf(b, "\tif !c.eval_%s() { return }\n", sanitizeIdent(d.Binding.Expr))
	case "for":
		fmt.Fprintf(b, "\tfor _, item := range c.iter_%s() {\n", sanitizeIdent(d.Binding.State))
		b.WriteString("\t\t_ = item\n")
		b.WriteString("\t}\n")
	case "class":
		fmt.Fprintf(b, "\t// ogon:class:%s=%s\n", d.Suffix, d.Binding.Expr)
	}
}

// sanitizeIdent turns an expression into a Go-friendly identifier
// fragment. We hash collisions are unlikely for tests.
func sanitizeIdent(expr string) string {
	var b strings.Builder
	for _, r := range expr {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteRune('_')
		}
	}
	if b.Len() == 0 {
		return "expr"
	}
	s := b.String()
	if s[0] >= '0' && s[0] <= '9' {
		s = "e" + s
	}
	return s
}

// quoteGoString renders a Go-quoted string literal.
func quoteGoString(s string) string {
	// Use strconv.Quote semantics manually to avoid the import
	// in tests that hot-link this code path.
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\n':
			b.WriteString(`\n`)
		case '\t':
			b.WriteString(`\t`)
		case '\r':
			b.WriteString(`\r`)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}
