// SPDX-License-Identifier: MIT
// Copyright (c) 2026 OgonFrameworks. All rights reserved.
//
// `ogon infra diff` drift report (INFRA-037). Computes the delta between
// repo artifacts and the last generation ledger. Drift surfaces as:
//   - drift: file exists and content hash ≠ ledger hash (user edited or stale)
//   - missing: ledger records a file but it is absent on disk
//   - extra: file exists on disk but not in ledger (user-added or pre-ogon)
//   - unchanged: hash matches ledger
//
// The report is read-only: the CLI never modifies files when running diff.

package infra

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
)

// DriftStatus enumerates the four drift dispositions.
type DriftStatus string

const (
	DriftUnchanged DriftStatus = "unchanged"
	DriftDrift     DriftStatus = "drift"
	DriftMissing   DriftStatus = "missing"
	DriftExtra     DriftStatus = "extra"
)

// DriftEntry is one row of the drift report.
type DriftEntry struct {
	Path   string      `json:"path"`
	Status DriftStatus `json:"status"`
	Reason string      `json:"reason,omitempty"`
}

// DriftReport is the full report surfaced by `ogon infra diff`.
type DriftReport struct {
	Entries []DriftEntry `json:"entries"`
}

// HasDrift reports whether any entry is drift/missing/extra.
func (r *DriftReport) HasDrift() bool {
	for _, e := range r.Entries {
		if e.Status != DriftUnchanged {
			return true
		}
	}
	return false
}

// Diff computes the drift report for a set of generated paths against the
// on-disk state. root is the repo root. paths is the union of all generators'
// Plan() output that the user has run at least once (recorded in the lock).
// Files on disk but absent from the ledger are reported as DriftExtra only
// when they live under infra/ (the generator's committed-artifact area).
func Diff(root string, lock *LockFile, paths []string) (*DriftReport, error) {
	report := &DriftReport{}
	seen := map[string]bool{}

	// Pass 1: ledger-known paths.
	for _, p := range paths {
		seen[p] = true
		full := filepath.Join(root, p)
		b, err := os.ReadFile(full)
		if err != nil {
			if os.IsNotExist(err) {
				report.Entries = append(report.Entries, DriftEntry{
					Path: p, Status: DriftMissing,
					Reason: "ledger records file but it is absent on disk",
				})
				continue
			}
			return nil, fmt.Errorf("read %s: %w", p, err)
		}
		actual := SHA256Hex(string(b))
		entry := lock.Lookup(p)
		if entry == nil {
			// file exists on disk, no ledger → could be a user-owned file in
			// the infra area, or a file that was generated but never recorded.
			report.Entries = append(report.Entries, DriftEntry{
				Path: p, Status: DriftExtra,
				Reason: "no ledger entry; file not generated by ogon",
			})
			continue
		}
		if actual == entry.SHA256 {
			report.Entries = append(report.Entries, DriftEntry{
				Path: p, Status: DriftUnchanged, Reason: "matches last generation",
			})
		} else {
			report.Entries = append(report.Entries, DriftEntry{
				Path: p, Status: DriftDrift,
				Reason: "content differs from last generation",
			})
		}
	}

	// Pass 2: scan <root>/infra/ for files not in the ledger. These are
	// "extra" — either pre-ogon or user-added.
	infraDir := filepath.Join(root, "infra")
	if _, err := os.Stat(infraDir); err == nil {
		extras, err := scanExtra(infraDir, root, seen)
		if err != nil {
			return nil, err
		}
		report.Entries = append(report.Entries, extras...)
	}

	sort.Slice(report.Entries, func(i, j int) bool { return report.Entries[i].Path < report.Entries[j].Path })
	return report, nil
}

// scanExtra walks dir and reports files not in seen as DriftExtra. The walk is
// limited to committed-artifact extensions (Dockerfile, .yml/.yaml, .tf, .sh,
// Makefile) to avoid flagging vendored or transient files.
func scanExtra(dir, root string, seen map[string]bool) ([]DriftEntry, error) {
	var out []DriftEntry
	walkErr := filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil
		}
		if info.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return nil
		}
		rel = filepath.ToSlash(rel)
		if seen[rel] {
			return nil
		}
		if !isArtifactExt(path) {
			return nil
		}
		out = append(out, DriftEntry{
			Path: rel, Status: DriftExtra,
			Reason: "file in infra/ area not recorded in ledger",
		})
		return nil
	})
	if walkErr != nil {
		return nil, walkErr
	}
	return out, nil
}

func isArtifactExt(path string) bool {
	switch {
	case filepath.Ext(path) == ".yml", filepath.Ext(path) == ".yaml",
		filepath.Ext(path) == ".tf", filepath.Ext(path) == ".sh":
		return true
	case filepath.Base(path) == "Dockerfile":
		return true
	case filepath.Base(path) == "Makefile":
		return true
	}
	return false
}
