// SPDX-License-Identifier: MIT
// Copyright (c) 2026 OgonFrameworks. All rights reserved.
//
// OGON-INFRA — generative infrastructure (Part XII).
// Config schema, ownership markers, generator interface. Everything this
// package emits lands under infra/ in the user's repo, is committed, is
// editable, and is regenerable. INFRA-001 / INFRA-038 / INFRA-039 / INFRA-040.

package infra

import (
	"fmt"
	"strings"
)

// Version is the infra generator surface version. Bumped when the emitted
// artifact shape changes in a way that requires regeneration.
const Version = "1.0.0"

// LicenseHeader is the canonical SPDX header prepended to every emitted
// artifact (Dockerfile, YAML, HCL, scripts). The header doubles as a
// human-visible license declaration and a stable generation-time anchor
// for `ogon infra diff` drift detection (INFRA-037).
const LicenseHeader = `# SPDX-License-Identifier: MIT
# Copyright (c) 2026 OgonFrameworks. All rights reserved.
#
# This file is generated by ogon infra (OGON-INFRA). Editable by default.
# Re-run "ogon infra gen" to refresh; --force required if you have local
# edits that diverge from the last generation (INFRA-038/040).
`

// Marker identifies a generation-time ownership tag embedded in file content.
type Marker string

const (
	// MarkGenerated is a passive tag indicating the file is generator output.
	// It does NOT make the file regenerable — only MarkOwned does.
	MarkGenerated Marker = "ogon:generated"
	// MarkOwned marks a file as owned by ogon. Owned files are safe to
	// regenerate without --force (unless the user has locally edited them —
	// see infra/idempotent.go).
	MarkOwned Marker = "ogon:owned"
	// MarkSeeded marks a file as a one-time seed: written once, then handed
	// to the user. Subsequent regeneration requires --force.
	MarkSeeded Marker = "ogon:seeded"
)

// MarkerLine returns the marker as a content comment line. The prefix is the
// language's comment character ("#" for Dockerfile/YAML/HCL, "//" for Go).
func (m Marker) MarkerLine(prefix string) string {
	return prefix + " " + string(m) + "\n"
}

// FileSpec is a single artifact emitted by a generator.
type FileSpec struct {
	// Path is the repo-relative path. Use forward slashes.
	Path string
	// Content is the full file bytes (text only; no encoding).
	Content string
	// Marker is the ownership marker to stamp at the top of Content. Zero
	// value means no marker — the file is treated as user-owned and requires
	// --force on regeneration (INFRA-038).
	Marker Marker
	// CommentPrefix is the file's comment character ("#" or "//").
	CommentPrefix string
	// Description is a one-line human-readable purpose, surfaced by --dry-run.
	Description string
}

// Stamped returns Content with the license header and marker line prepended.
// If Marker is zero, only the license header is prepended (the file is
// treated as user-owned and a one-time seed; --force is required on
// regeneration). INFRA-038.
func (s FileSpec) Stamped() string {
	var b strings.Builder
	b.WriteString(LicenseHeader)
	if s.Marker != "" {
		b.WriteString(s.Marker.MarkerLine(s.CommentPrefix))
	}
	b.WriteString("\n")
	b.WriteString(s.Content)
	return b.String()
}

// Generator is the contract every infra target implements. The CLI's
// `ogon infra gen <target>` dispatches to one Generator per target.
type Generator interface {
	// Name is the target name surfaced in `ogon infra gen <name>`.
	Name() string
	// Plan returns the repo-relative paths this generator would write, in
	// stable lexicographic order. Used by --dry-run and drift detection.
	Plan(cfg *InfraConfig) []string
	// Generate produces the full file specs. The CLI applies ownership rules
	// (see idempotent.go) and writes only to marker-unowned or --force paths.
	Generate(cfg *InfraConfig) ([]FileSpec, error)
}

// InfraConfig is the input shape for every generator (INFRA-001). It is
// intentionally a flat, plain struct so ogon.yaml can hydrate it via the
// generic config layer without per-field hooks.
type InfraConfig struct {
	App       AppConfig
	Image     ImageConfig
	Replicas  int
	Resources ResourceConfig
	Probes    ProbeConfig
	Cloud     string // aws|gcp|azure (terraform target)
	Env       string // local|dev|prod (env matrix INFRA-026)
	Registry  RegistryConfig
	Compose   ComposeConfig
	K8s       K8sConfig
	Terraform TerraformConfig
	GitHub    GitHubConfig
	Release   ReleaseConfig
	Database  DatabaseConfig
	Cache     CacheConfig
	Mail      MailConfig
	Secrets   []SecretRef
}

// AppConfig describes the application under deployment.
type AppConfig struct {
	Name    string // binary + service name
	Version string // semver, stamped into image and binary
	Module  string // Go module path (e.g. github.com/acme/app)
	MainPkg string // build target, default ./cmd/<App.Name>
	Port    int    // HTTP listen port
	FIPS    bool   // build with FIPS-mode crypto (INFRA-004)
}

// ImageConfig describes the container image produced by `docker build`.
type ImageConfig struct {
	Base       string // default gcr.io/distroless/static-debian12
	Repository string // e.g. acme/app
	Tag        string // override; default = release tag
	MaxMB      int    // default 30 (INFRA-059 hello budget)
}

// ResourceConfig holds k8s/terraform resource defaults. INFRA-043 baseline
// is 250m CPU request / 512Mi memory request.
type ResourceConfig struct {
	CPURequest string
	MemRequest string
	CPULimit   string
	MemLimit   string
}

// ProbeConfig holds k8s probe paths and timing.
type ProbeConfig struct {
	LivenessPath        string // default /healthz
	ReadinessPath       string // default /readyz
	StartupPath         string // default /healthz/startup
	InitialDelaySeconds int
	PeriodSeconds       int
	TimeoutSeconds      int
	FailureThreshold    int
}

// RegistryConfig describes the OCI registry push target. INFRA-032 docs
// (GHCR/ECR/GAR auth) are emitted alongside the registry push helper.
type RegistryConfig struct {
	Provider string // ghcr|ecr|gar|none
	Host     string // ghcr.io, <acct>.dkr.ecr.<region>.amazonaws.com, <region>-docker.pkg.dev
	Account  string // GitHub user/org, AWS account ID, GCP project
}

// ComposeConfig drives the dev stack (INFRA-006/007) and PR preview env
// (INFRA-055).
type ComposeConfig struct {
	PostgresVersion string
	RedisVersion    string
	MailpitVersion  string
	Adminer         bool
	PreviewProfile  string // compose profile name for PR preview (default "preview")
}

// K8sConfig drives all k8s manifests.
type K8sConfig struct {
	Namespace       string
	IngressHost     string
	TLSEnabled      bool
	CertIssuer      string // cert-manager Issuer name (INFRA-045)
	ExternalDNS     bool   // enable external-dns annotations (INFRA-046)
	HPACPUTarget    int    // percent target (default 75) (INFRA-044)
	HPAMemTarget    int
	PDBMinAvailable int
	NetworkPolicy   string // default-deny|scoped|none
	SpotToleration  bool   // spot pool toleration sample (INFRA-067)
	NodeAffinity    string // node-pool label, e.g. node-role.kubernetes.io/app
	Worker          WorkerConfig
	CronSchedules   []CronSchedule
}

// WorkerConfig drives the separate worker Deployment (INFRA-015).
type WorkerConfig struct {
	Enabled  bool
	Replicas int
	Command  []string
}

// CronSchedule drives CronJobs for schedules (INFRA-016).
type CronSchedule struct {
	Name     string
	Schedule string // cron expression
	Command  []string
}

// TerraformConfig drives the AWS provider (INFRA-020/063/064/050).
type TerraformConfig struct {
	Region      string
	AccountID   string
	MultiRegion bool
	IAMDBAuth   bool
	VPCPrivate  bool // default true (INFRA-064)
}

// GitHubConfig drives the ci/deploy workflows (INFRA-034).
type GitHubConfig struct {
	Repo   string // owner/name
	Cloud  string // for deploy.yml per-cloud matrix
	Runner string // runner label; default ubuntu-latest
}

// ReleaseConfig drives release-time stamping (INFRA-029..032).
type ReleaseConfig struct {
	SemVer string
	GitSHA string
	Push   bool
	SBOM   bool // INFRA-057
	Trivy  bool // INFRA-058
	Sign   bool // SEC-074 signed images
}

// DatabaseConfig drives postgres/rds settings.
type DatabaseConfig struct {
	Engine  string // default postgres
	Version string
	Name    string
	User    string
}

// CacheConfig drives redis/elasticache settings.
type CacheConfig struct {
	Engine  string
	Version string
}

// MailConfig drives mailpit dev mail.
type MailConfig struct {
	Engine  string
	Version string
}

// SecretRef is a yaml→k8s Secret key mapping (INFRA-027).
type SecretRef struct {
	Name   string // ogon.yaml key path, e.g. database.url
	Secret string // k8s Secret name
	Key    string // k8s Secret key
	EnvVar string // container env var to receive the value
}

// DefaultConfig returns the canonical defaults used when ogon.yaml does not
// override. Defaults are deliberately conservative: distroless/static base,
// 250m/512Mi baseline resources (INFRA-043), 30 MB hello image budget
// (INFRA-059), 30s startup probe failure threshold (INFRA-060).
func DefaultConfig() *InfraConfig {
	return &InfraConfig{
		App: AppConfig{
			Name: "app", Version: "0.1.0", Module: "github.com/acme/app",
			MainPkg: "./cmd/app", Port: 8080, FIPS: false,
		},
		Image: ImageConfig{
			Base: "gcr.io/distroless/static-debian12", Repository: "acme/app",
			MaxMB: 30,
		},
		Replicas: 2,
		Resources: ResourceConfig{
			CPURequest: "250m", MemRequest: "512Mi",
			CPULimit: "500m", MemLimit: "1Gi",
		},
		Probes: ProbeConfig{
			LivenessPath: "/healthz", ReadinessPath: "/readyz",
			StartupPath:         "/healthz/startup",
			InitialDelaySeconds: 0, PeriodSeconds: 10,
			TimeoutSeconds: 1, FailureThreshold: 30,
		},
		Cloud: "aws", Env: "dev",
		Registry: RegistryConfig{Provider: "ghcr", Host: "ghcr.io", Account: "acme"},
		Compose: ComposeConfig{
			PostgresVersion: "16", RedisVersion: "7", MailpitVersion: "latest",
			Adminer: false, PreviewProfile: "preview",
		},
		K8s: K8sConfig{
			Namespace: "default", IngressHost: "app.example.com",
			TLSEnabled: true, CertIssuer: "letsencrypt-prod",
			ExternalDNS: true, HPACPUTarget: 75, HPAMemTarget: 75,
			PDBMinAvailable: 1, NetworkPolicy: "default-deny",
			Worker: WorkerConfig{Enabled: true, Replicas: 1, Command: []string{"/app", "worker"}},
		},
		Terraform: TerraformConfig{
			Region: "us-east-1", AccountID: "000000000000",
			MultiRegion: false, IAMDBAuth: false, VPCPrivate: true,
		},
		GitHub:   GitHubConfig{Repo: "acme/app", Cloud: "aws", Runner: "ubuntu-latest"},
		Release:  ReleaseConfig{SemVer: "0.1.0", Push: true, SBOM: true, Trivy: true, Sign: false},
		Database: DatabaseConfig{Engine: "postgres", Version: "16", Name: "app", User: "app"},
		Cache:    CacheConfig{Engine: "redis", Version: "7"},
		Mail:     MailConfig{Engine: "mailpit", Version: "latest"},
	}
}

// Envs returns the three standard environments (local/dev/prod) (INFRA-026).
func (c *InfraConfig) Envs() []string { return []string{"local", "dev", "prod"} }

// Validate returns nil if the config is internally consistent. The CLI calls
// this before any generator runs so misconfigurations surface as OGON-K
// diagnostics rather than malformed artifacts.
func (c *InfraConfig) Validate() error {
	if c.App.Name == "" {
		return fmt.Errorf("infra: app.name is required (INFRA-001)")
	}
	if c.App.Port == 0 {
		return fmt.Errorf("infra: app.port is required")
	}
	if c.Cloud != "" {
		switch c.Cloud {
		case "aws", "gcp", "azure":
		default:
			return fmt.Errorf("infra: cloud %q is not aws|gcp|azure", c.Cloud)
		}
	}
	if c.Env != "" {
		switch c.Env {
		case "local", "dev", "prod":
		default:
			return fmt.Errorf("infra: env %q is not local|dev|prod", c.Env)
		}
	}
	return nil
}

// EOL
