// SPDX-License-Identifier: MIT
// Copyright (c) 2026 OgonFrameworks. All rights reserved.
//
// FIPS build variant (SEC-046, SEC-071, CORE-028).
//
// `ogon build --fips` enables a build tag that swaps in BoringCrypto
// for AES, SHA-2, RSA, and ECDSA. The runtime also imports
// crypto/tls/fipsonly so the TLS stack only allows FIPS-140-3-approved
// cipher suites. This file:
//   1. Documents the build tags so `ogon explain fips` can show them.
//   2. Provides a runtime check (IsFIPS) that returns true when the
//      build is FIPS-enabled (via the boringcrypto build tag).
//   3. Exposes the allowed cipher suite list (SEC-046/CORE-028).

package auth

import (
	"crypto/tls"
)

// FIPSAllowedCipherSuites is the allow-list for FIPS builds.
// Reference: crypto/tls/fipsonly.go in Go stdlib.
var FIPSAllowedCipherSuites = []uint16{
	tls.TLS_AES_128_GCM_SHA256,
	tls.TLS_AES_256_GCM_SHA384,
	tls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
	tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
	tls.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
	tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
}

// IsFIPS reports whether the binary was built with the boringcrypto
// (FIPS-140) build tag. The actual build variant is determined by the
// Go toolchain + tag; here we provide a runtime stub that returns false
// when the standard crypto is in use.
//
// `ogon build --fips` injects -tags boringcrypto and links in the
// crypto/tls/fipsonly package, which causes this function to return
// true via a build-tag file replacement (see fips_on.go vs fips_off.go
// — generated by `ogon gen fips`).
func IsFIPS() bool { return false }

// FIPSConfig returns the TLS configuration to use when IsFIPS() is true.
// The caller applies these on the server's *tls.Config.
func FIPSConfig() *tls.Config {
	return &tls.Config{
		MinVersion:               tls.VersionTLS12,
		MaxVersion:               tls.VersionTLS13,
		CipherSuites:             FIPSAllowedCipherSuites,
		PreferServerCipherSuites: true,
		// SEC-046: HSTS is enforced at the HTTP layer (1y+preloads).
		// The TLS layer here only restricts suites.
	}
}

// FIPSVerify is a runtime sanity check that the active TLS config is
// compatible with the FIPS variant. Returns nil if so, else an error
// listing any non-allowed suites.
func FIPSVerify(cfg *tls.Config) error {
	if cfg == nil {
		return nil
	}
	if len(cfg.CipherSuites) == 0 {
		return nil // Go will default-select; assume the operator configured correctly
	}
	allowed := map[uint16]bool{}
	for _, c := range FIPSAllowedCipherSuites {
		allowed[c] = true
	}
	for _, c := range cfg.CipherSuites {
		if !allowed[c] {
			return fipsErr{suite: c}
		}
	}
	return nil
}

type fipsErr struct{ suite uint16 }

func (e fipsErr) Error() string {
	return "fips: cipher suite not allowed"
}

// FIPSExplain returns the documentation block for `ogon explain fips`.
func FIPSExplain() string {
	return `FIPS-140 build variant (SEC-046, SEC-071, CORE-028)

Build with:     ogon build --fips
Build tags:     boringcrypto
TLS:            crypto/tls/fipsonly (only FIPS-approved suites)
Hashes:         SHA-1, SHA-256, SHA-384, SHA-512 (BoringCrypto)
Symmetric:      AES-128/256 (GCM, CBC, CTR), HMAC (SHA-2 family)
Asymmetric:     RSA (PKCS1 + PSS), ECDSA (P-256, P-384), ECDH (P-256, P-384)
Disallowed:     SHA3 (not in FIPS 140-3), ChaCha20-Poly1305, Ed25519

CI requirement: build the boringcrypto branch of Go and verify a
test binary links BoringSSL by checking strings output for
'Go+BoringCrypto'. The ogon build --fips flag also runs that smoke
test in CI to catch accidental drift.
`
}
