// SPDX-License-Identifier: MIT
// Copyright (c) 2026 OgonFrameworks. All rights reserved.
//
// Live component registry (UI-008). Generated by the compiler
// pipeline, the registry maps component names to their wire-handler
// constructors so the runtime can spin up instances on demand.

package runtime

import (
	"errors"
	"sync"
)

// Component is the runtime-side interface for a generated `.ogon`
// component. It owns server-side state and dispatches wire events.
type Component interface {
	// Name returns the component name (e.g. "Chat").
	Name() string
	// HandleEvent dispatches a typed event payload to a handler.
	HandleEvent(name string, payload map[string]any) error
	// Render returns the HTML for the current state.
	Render() string
}

// ComponentCtor constructs a fresh component instance. The registry
// calls the constructor when a new session mounts the component.
type ComponentCtor func() Component

// Registry maps component names to constructors.
type Registry struct {
	mu    sync.RWMutex
	ctors map[string]ComponentCtor
}

// NewRegistry constructs an empty registry.
func NewRegistry() *Registry { return &Registry{ctors: map[string]ComponentCtor{}} }

// Register adds (or replaces) a component constructor.
func (r *Registry) Register(name string, ctor ComponentCtor) {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.ctors[name] = ctor
}

// Get returns the constructor for the supplied name.
func (r *Registry) Get(name string) (ComponentCtor, bool) {
	r.mu.RLock()
	defer r.mu.RUnlock()
	ctor, ok := r.ctors[name]
	return ctor, ok
}

// MustNew constructs an instance or panics (dev only).
func (r *Registry) MustNew(name string) Component {
	ctor, ok := r.Get(name)
	if !ok {
		panic("ogon/ui: unknown component " + name)
	}
	return ctor()
}

// New returns a fresh component instance or ErrUnknownComponent.
func (r *Registry) New(name string) (Component, error) {
	ctor, ok := r.Get(name)
	if !ok {
		return nil, ErrUnknownComponent
	}
	return ctor(), nil
}

// ErrUnknownComponent is returned by New when no constructor is
// registered for the requested name.
var ErrUnknownComponent = errors.New("ogon/ui: unknown component")
