// SPDX-License-Identifier: MIT
// Copyright (c) 2026 OgonFrameworks. All rights reserved.
//
// Helm chart stub. Emits a minimal but valid Helm chart for projects that
// deploy via Helm rather than raw k8s manifests. The chart wraps the same
// manifests infra/k8s produces, parameterized via values.yaml.
//
// This is a stub: it emits Chart.yaml, values.yaml, and a single
// templates/_all.yaml that wraps the standard manifests with `{{ }}`
// Helm interpolations. Projects that want richer chart behavior hand-edit
// (the file is MarkSeeded — --force required to regenerate).

package helm

import (
	"fmt"
	"strings"
	"text/template"

	"github.com/OgonFrameworks/ogon.go/infra"
)

// Generator implements infra.Generator for the helm target.
type Generator struct{}

func (Generator) Name() string { return "helm" }

func (Generator) Plan(cfg *infra.InfraConfig) []string {
	return []string{
		"infra/helm/Chart.yaml",
		"infra/helm/values.yaml",
		"infra/helm/templates/_all.yaml",
		"infra/helm/templates/_helpers.tpl",
		"infra/helm/.helmignore",
	}
}

func (Generator) Generate(cfg *infra.InfraConfig) ([]infra.FileSpec, error) {
	chart, err := GenerateChart(cfg)
	if err != nil {
		return nil, err
	}
	vals, err := GenerateValues(cfg)
	if err != nil {
		return nil, err
	}
	all, err := GenerateTemplatesAll(cfg)
	if err != nil {
		return nil, err
	}
	help, err := GenerateHelpers(cfg)
	if err != nil {
		return nil, err
	}
	ignore, err := GenerateHelmignore(cfg)
	if err != nil {
		return nil, err
	}
	return []infra.FileSpec{chart, vals, all, help, ignore}, nil
}

// GenerateChart emits infra/helm/Chart.yaml.
func GenerateChart(cfg *infra.InfraConfig) (infra.FileSpec, error) {
	tpl := template.Must(template.New("chart").Parse(chartTemplate))
	var b strings.Builder
	if err := tpl.Execute(&b, cfg); err != nil {
		return infra.FileSpec{}, fmt.Errorf("helm chart template: %w", err)
	}
	return infra.FileSpec{
		Path: "infra/helm/Chart.yaml", Content: b.String(),
		Marker: infra.MarkOwned, CommentPrefix: "#",
		Description: "Helm Chart.yaml",
	}, nil
}

const chartTemplate = `apiVersion: v2
name: {{.App.Name}}
description: {{.App.Name}} on Kubernetes (Helm chart generated by OGON-INFRA)
type: application
version: 0.1.0
appVersion: "{{.App.Version}}"
keywords:
  - ogon
  - web
maintainers:
  - name: OgonFrameworks
`

// GenerateValues emits infra/helm/values.yaml.
func GenerateValues(cfg *infra.InfraConfig) (infra.FileSpec, error) {
	tpl := template.Must(template.New("vals").Parse(valuesTemplate))
	var b strings.Builder
	if err := tpl.Execute(&b, cfg); err != nil {
		return infra.FileSpec{}, fmt.Errorf("helm values template: %w", err)
	}
	return infra.FileSpec{
		Path: "infra/helm/values.yaml", Content: b.String(),
		Marker: infra.MarkSeeded, CommentPrefix: "#",
		Description: "Helm values.yaml (seeded; edit by hand)",
	}, nil
}

const valuesTemplate = `image:
  repository: {{.Image.Repository}}
  tag: {{.App.Version}}
  pullPolicy: IfNotPresent

replicas: {{.Replicas}}

resources:
  requests:
    cpu: {{.Resources.CPURequest}}
    memory: {{.Resources.MemRequest}}
  limits:
    cpu: {{.Resources.CPULimit}}
    memory: {{.Resources.MemLimit}}

probes:
  livenessPath: {{.Probes.LivenessPath}}
  readinessPath: {{.Probes.ReadinessPath}}
  startupPath: {{.Probes.StartupPath}}

worker:
  enabled: {{.K8s.Worker.Enabled}}
  replicas: {{.K8s.Worker.Replicas}}

ingress:
  host: {{.K8s.IngressHost}}
  tls: {{.K8s.TLSEnabled}}
  certIssuer: {{.K8s.CertIssuer}}

hpa:
  cpuTarget: {{.K8s.HPACPUTarget}}
  memTarget: {{.K8s.HPAMemTarget}}

pdb:
  minAvailable: {{.K8s.PDBMinAvailable}}

networkPolicy: {{.K8s.NetworkPolicy}}

nodeAffinity: {{.K8s.NodeAffinity}}
spotToleration: {{.K8s.SpotToleration}}
`

// GenerateTemplatesAll emits the wrapped manifests.
func GenerateTemplatesAll(cfg *infra.InfraConfig) (infra.FileSpec, error) {
	const all = `{{- include "ogon.labels" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ogon.fullname" . }}
  labels:
    {{- include "ogon.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "ogon.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ogon.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: {{ include "ogon.fullname" . }}-config
            - secretRef:
                name: {{ include "ogon.fullname" . }}-secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
          startupProbe:
            httpGet:
              path: {{ .Values.probes.startupPath }}
              port: http
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.livenessPath }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readinessPath }}
              port: http
          lifecycle:
            preStop:
              exec:
                command: ["/app", "drain"]
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ogon.fullname" . }}
  labels:
    {{- include "ogon.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "ogon.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
`
	return infra.FileSpec{
		Path: "infra/helm/templates/_all.yaml", Content: all,
		Marker: infra.MarkOwned, CommentPrefix: "#",
		Description: "Helm templates: wrapped k8s manifests (INFRA-008..015)",
	}, nil
}

// GenerateHelpers emits templates/_helpers.tpl.
func GenerateHelpers(cfg *infra.InfraConfig) (infra.FileSpec, error) {
	const help = `{{- define "ogon.fullname" -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- define "ogon.labels" -}}
app.kubernetes.io/name: {{ .Chart.Name }}
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
{{- end -}}

{{- define "ogon.selectorLabels" -}}
app.kubernetes.io/name: {{ .Chart.Name }}
app.kubernetes.io/instance: {{ .Release.Name }}
ogonframeworks.dev/role: web
{{- end -}}
`
	return infra.FileSpec{
		Path: "infra/helm/templates/_helpers.tpl", Content: help,
		Marker: infra.MarkOwned, CommentPrefix: "#",
		Description: "Helm helper templates",
	}, nil
}

// GenerateHelmignore emits infra/helm/.helmignore.
func GenerateHelmignore(cfg *infra.InfraConfig) (infra.FileSpec, error) {
	const ignore = `# Patterns to ignore when packaging the chart.
.git
.gitignore
.ogon-infra.lock
*.md
*.tf
*.tfstate
*.tfstate.*
README.md
LICENSE
`
	return infra.FileSpec{
		Path: "infra/helm/.helmignore", Content: ignore,
		Marker: infra.MarkOwned, CommentPrefix: "#",
		Description: "Helm .helmignore",
	}, nil
}
