// SPDX-License-Identifier: MIT
// Copyright (c) 2026 OgonFrameworks. All rights reserved.
//
// di/codegen.go: emits generated/di/di_gen.go — a statically typed container
// of direct calls (DI-004/018/022). No `map[string]any` at runtime. The
// output is byte-stable for identical inputs (DI-020) and contains no
// reflection (DI-022).
//
// Generated container shape:
//
//      package di
//
//      type Deps struct {
//          // one field per external dependency (no provider)
//          DB    *record.Pool
//          Cfg   *config.Schema
//      }
//
//      type Container struct {
//          deps     *Deps
//          cleanups []func() error
//          // one sync.Once + typed field per singleton provider
//          userSvcOnce sync.Once
//          userSvc     *services.UserService
//      }
//
//      type Scope struct {
//          // one sync.Once + typed field per scoped provider
//          cartSvcOnce sync.Once
//          cartSvc     *services.CartService
//      }
//
//      func New(deps *Deps) *Container { ... }
//      func (c *Container) UserService() *services.UserService { ... }
//      func (c *Container) CartService(ctx context.Context) *services.CartService { ... }
//      func (c *Container) Close() error { ... }

package di

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// CodegenOptions controls di_gen.go emission.
type CodegenOptions struct {
	// PackageName is the package name for the generated file (default "di").
	PackageName string
	// OutputPath is the absolute path of the file to write.
	OutputPath string
	// HeaderComment is prepended verbatim if non-empty.
	HeaderComment string
}

// DefaultCodegenOptions returns sensible defaults for a project-rooted build.
func DefaultCodegenOptions(outputPath string) CodegenOptions {
	return CodegenOptions{
		PackageName:   "di",
		OutputPath:    outputPath,
		HeaderComment: "Code generated by ogon di. DO NOT EDIT.",
	}
}

// Generate writes the typed container file for the supplied graph. Returns
// the rendered bytes (after gofmt) so callers can diff or snapshot. The
// output is byte-stable for identical graph inputs (DI-020).
func Generate(g *Graph, opts CodegenOptions) ([]byte, error) {
	if g == nil {
		return nil, errors.New("di: nil graph")
	}
	if opts.PackageName == "" {
		opts.PackageName = "di"
	}
	if opts.OutputPath == "" {
		return nil, errors.New("di: empty output path")
	}
	order, err := g.TopoSort()
	if err != nil {
		return nil, err
	}
	externals := externalsOf(order, g)
	src := renderSource(opts.PackageName, opts.HeaderComment, order, externals, g)
	formatted, err := format.Source(src)
	if err != nil {
		// Write the unformatted source next to the target so the user can
		// inspect the syntax error before we exit.
		_ = os.WriteFile(opts.OutputPath+".debug", src, 0o644)
		return nil, fmt.Errorf("di: gofmt failed: %w (raw source written to %s.debug)", err, opts.OutputPath)
	}
	if err := os.MkdirAll(filepath.Dir(opts.OutputPath), 0o755); err != nil {
		return nil, fmt.Errorf("di: mkdir %s: %w", filepath.Dir(opts.OutputPath), err)
	}
	if err := os.WriteFile(opts.OutputPath, formatted, 0o644); err != nil {
		return nil, fmt.Errorf("di: write %s: %w", opts.OutputPath, err)
	}
	return formatted, nil
}

// externalDep is a required type with no provider. The generated Container
// holds these in a Deps struct that the caller supplies.
type externalDep struct {
	Field string
	Type  TypeRef
}

// externalsOf collects the unique external deps across all providers, in
// stable order (by Ref string).
func externalsOf(order []Provider, g *Graph) []externalDep {
	seen := map[Ref]bool{}
	var out []externalDep
	for _, p := range order {
		for _, r := range p.Requires {
			key := r.Key()
			if isBuiltinRef(key) {
				continue
			}
			if _, ok := g.providers[key]; ok {
				continue
			}
			if seen[key] {
				continue
			}
			seen[key] = true
			out = append(out, externalDep{Field: depFieldName(r), Type: r})
		}
	}
	sort.Slice(out, func(i, j int) bool {
		return out[i].Type.Key().String() < out[j].Type.Key().String()
	})
	return out
}

// depFieldName derives a Go-identifier field name from a TypeRef. Strips
// pointer/array markers and lowercases the first letter.
func depFieldName(t TypeRef) string {
	name := t.Name
	name = strings.TrimPrefix(name, "*")
	name = strings.TrimPrefix(name, "[]")
	name = strings.TrimPrefix(name, "map[]")
	return upperFirst(name)
}

// upperFirst capitalises the first byte.
func upperFirst(s string) string {
	if s == "" {
		return s
	}
	r := []byte(s)
	if r[0] >= 'a' && r[0] <= 'z' {
		r[0] -= 'a' - 'A'
	}
	return string(r)
}

// renderSource produces the unformatted Go source for the container.
func renderSource(pkg, header string, order []Provider, externals []externalDep, g *Graph) []byte {
	var b bytes.Buffer
	fmt.Fprintln(&b, "// SPDX-License-Identifier: MIT")
	fmt.Fprintln(&b, "// Copyright (c) 2026 OgonFrameworks. All rights reserved.")
	fmt.Fprintln(&b, "//")
	if header != "" {
		for _, line := range strings.Split(header, "\n") {
			fmt.Fprintln(&b, "//", line)
		}
	}
	fmt.Fprintln(&b, "//")
	fmt.Fprintf(&b, "// Generated: %s\n", time.Now().UTC().Format("2006-01-02T15:04:05Z"))
	fmt.Fprintf(&b, "// Providers: %d (singleton=%d scoped=%d transient=%d)\n",
		len(order),
		countByLifetime(order, LifetimeSingleton),
		countByLifetime(order, LifetimeScoped),
		countByLifetime(order, LifetimeTransient),
	)
	fmt.Fprintf(&b, "// External deps: %d\n", len(externals))
	fmt.Fprintln(&b, "")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	fmt.Fprintln(&b, "import (")
	if needsContext(order, externals) {
		fmt.Fprintln(&b, "\t\"context\"")
	}
	fmt.Fprintln(&b, "\t\"sync\"")
	imps := collectImports(order, externals)
	for _, imp := range imps {
		fmt.Fprintf(&b, "\t%s %q\n", imp.alias, imp.path)
	}
	fmt.Fprintln(&b, ")")
	fmt.Fprintln(&b, "")

	// Deps struct (external dependencies).
	fmt.Fprintln(&b, "// Deps carries the external dependencies the generated container")
	fmt.Fprintln(&b, "// cannot build itself (e.g. *record.Pool, *config.Schema). The caller")
	fmt.Fprintln(&b, "// constructs Deps and passes it to New (DI-018: no map[string]any).")
	fmt.Fprintln(&b, "type Deps struct {")
	for _, e := range externals {
		fmt.Fprintf(&b, "\t%s %s\n", e.Field, qualifiedType(e.Type, "", ""))
	}
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b, "")

	// Container struct.
	fmt.Fprintln(&b, "// Container is the generated DI container (DI-018). All fields are")
	fmt.Fprintln(&b, "// typed; there are no map[string]any lookups at runtime (DI-022).")
	fmt.Fprintln(&b, "type Container struct {")
	fmt.Fprintln(&b, "\tdeps     *Deps")
	fmt.Fprintln(&b, "\tmu       sync.Mutex")
	fmt.Fprintln(&b, "\tcleanups []func() error")
	for _, p := range order {
		if p.Lifetime == LifetimeSingleton {
			fmt.Fprintf(&b, "\t%sOnce sync.Once\n", lowerFirst(p.Name))
			fmt.Fprintf(&b, "\t%s     %s\n", lowerFirst(p.Name), qualifiedType(p.Provides, p.PkgPath, p.PkgName))
		}
	}
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b, "")

	// Scope struct (per-request; only emitted when there are scoped providers).
	scoped := providersByLifetime(order, LifetimeScoped)
	if len(scoped) > 0 {
		fmt.Fprintln(&b, "// Scope is the per-request scope (DI-006). One field per scoped")
		fmt.Fprintln(&b, "// provider; fully typed (no map[string]any).")
		fmt.Fprintln(&b, "type Scope struct {")
		fmt.Fprintln(&b, "\tmu sync.Mutex")
		for _, p := range scoped {
			fmt.Fprintf(&b, "\t%sOnce sync.Once\n", lowerFirst(p.Name))
			fmt.Fprintf(&b, "\t%s     %s\n", lowerFirst(p.Name), qualifiedType(p.Provides, p.PkgPath, p.PkgName))
		}
		fmt.Fprintln(&b, "}")
		fmt.Fprintln(&b, "")
		fmt.Fprintln(&b, "// scopeKey is the unexported context key for the per-request scope.")
		fmt.Fprintln(&b, "type scopeKey struct{}")
		fmt.Fprintln(&b, "")
		fmt.Fprintln(&b, "// WithScope binds a per-request scope to ctx.")
		fmt.Fprintln(&b, "func WithScope(ctx context.Context, s *Scope) context.Context {")
		fmt.Fprintln(&b, "\treturn context.WithValue(ctx, scopeKey{}, s)")
		fmt.Fprintln(&b, "}")
		fmt.Fprintln(&b, "")
		fmt.Fprintln(&b, "// ScopeFrom returns the scope bound to ctx, or nil if none.")
		fmt.Fprintln(&b, "func ScopeFrom(ctx context.Context) *Scope {")
		fmt.Fprintln(&b, "\ts, _ := ctx.Value(scopeKey{}).(*Scope)")
		fmt.Fprintln(&b, "\treturn s")
		fmt.Fprintln(&b, "}")
		fmt.Fprintln(&b, "")
		fmt.Fprintln(&b, "// NewScope returns a fresh per-request scope.")
		fmt.Fprintln(&b, "func NewScope() *Scope {")
		fmt.Fprintln(&b, "\treturn &Scope{}")
		fmt.Fprintln(&b, "}")
		fmt.Fprintln(&b, "")
	}

	// New constructor.
	fmt.Fprintln(&b, "// New constructs a Container wired to the supplied external deps.")
	fmt.Fprintln(&b, "// Singleton providers are lazily built on first call (DI-030).")
	fmt.Fprintln(&b, "func New(deps *Deps) *Container {")
	fmt.Fprintln(&b, "\tif deps == nil {")
	fmt.Fprintln(&b, "\t\tpanic(\"di: nil Deps\")")
	fmt.Fprintln(&b, "\t}")
	fmt.Fprintln(&b, "\treturn &Container{deps: deps}")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b, "")

	// Deps() accessor returns the underlying external-deps struct.
	fmt.Fprintln(&b, "// Deps returns the external-deps struct (for advanced wiring).")
	fmt.Fprintln(&b, "func (c *Container) Deps() *Deps { return c.deps }")
	fmt.Fprintln(&b, "")

	// One accessor per provider.
	for _, p := range order {
		writeProviderAccessor(&b, p, g)
	}

	// Close drains cleanups in reverse-init order (DI-013).
	fmt.Fprintln(&b, "// Close runs registered cleanups in LIFO order (DI-013).")
	fmt.Fprintln(&b, "func (c *Container) Close() error {")
	fmt.Fprintln(&b, "\tc.mu.Lock()")
	fmt.Fprintln(&b, "\tdefer c.mu.Unlock()")
	fmt.Fprintln(&b, "\tvar firstErr error")
	fmt.Fprintln(&b, "\tfor i := len(c.cleanups) - 1; i >= 0; i-- {")
	fmt.Fprintln(&b, "\t\tif err := c.cleanups[i](); err != nil && firstErr == nil {")
	fmt.Fprintln(&b, "\t\t\tfirstErr = err")
	fmt.Fprintln(&b, "\t\t}")
	fmt.Fprintln(&b, "\t}")
	fmt.Fprintln(&b, "\tc.cleanups = nil")
	fmt.Fprintln(&b, "\treturn firstErr")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b, "")
	return b.Bytes()
}

// writeProviderAccessor emits the accessor method for a single provider.
func writeProviderAccessor(b *bytes.Buffer, p Provider, g *Graph) {
	recv := qualifiedType(p.Provides, p.PkgPath, p.PkgName)
	switch p.Lifetime {
	case LifetimeSingleton:
		writeSingletonAccessor(b, p, recv, g)
	case LifetimeScoped:
		writeScopedAccessor(b, p, recv, g)
	case LifetimeTransient:
		writeTransientAccessor(b, p, recv, g)
	}
}

// writeSingletonAccessor emits:
//
//	func (c *Container) Name() T {
//	    c.nameOnce.Do(func() { c.name = <ctor>(...) ; optional cleanup registration })
//	    return c.name
//	}
func writeSingletonAccessor(b *bytes.Buffer, p Provider, recv string, g *Graph) {
	field := lowerFirst(p.Name)
	fmt.Fprintf(b, "// %s returns the singleton %s (DI-005). Built lazily on first call.\n", p.Name, recv)
	fmt.Fprintf(b, "// Source: %s\n", p.Position())
	fmt.Fprintf(b, "func (c *Container) %s() %s {\n", p.Name, recv)
	fmt.Fprintf(b, "\tc.%sOnce.Do(func() {\n", field)
	emitConstructorBody(b, p, g, "\t\t", "c", "c."+field)
	fmt.Fprintf(b, "\t})\n")
	fmt.Fprintf(b, "\treturn c.%s\n", field)
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "")
}

// writeScopedAccessor emits:
//
//	func (c *Container) Name(ctx context.Context) T {
//	    s := ScopeFrom(ctx)
//	    if s == nil { s = NewScope() }
//	    s.nameOnce.Do(func() { s.name = <ctor>(...) })
//	    return s.name
//	}
func writeScopedAccessor(b *bytes.Buffer, p Provider, recv string, g *Graph) {
	field := lowerFirst(p.Name)
	fmt.Fprintf(b, "// %s returns a per-request %s (DI-006). Cached in the scope bound\n", p.Name, recv)
	fmt.Fprintf(b, "// to ctx. If ctx carries no scope, a fresh ephemeral scope is used.\n")
	fmt.Fprintf(b, "// Source: %s\n", p.Position())
	fmt.Fprintf(b, "func (c *Container) %s(ctx context.Context) %s {\n", p.Name, recv)
	fmt.Fprintf(b, "\ts := ScopeFrom(ctx)\n")
	fmt.Fprintf(b, "\tif s == nil {\n")
	fmt.Fprintf(b, "\t\ts = NewScope()\n")
	fmt.Fprintf(b, "\t}\n")
	fmt.Fprintf(b, "\ts.%sOnce.Do(func() {\n", field)
	emitConstructorBody(b, p, g, "\t\t", "c", "s."+field)
	fmt.Fprintf(b, "\t})\n")
	fmt.Fprintf(b, "\treturn s.%s\n", field)
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "")
}

// writeTransientAccessor emits a fresh instance on every call.
func writeTransientAccessor(b *bytes.Buffer, p Provider, recv string, g *Graph) {
	fmt.Fprintf(b, "// %s returns a fresh %s on every call (DI-005 transient).\n", p.Name, recv)
	fmt.Fprintf(b, "// Source: %s\n", p.Position())
	fmt.Fprintf(b, "func (c *Container) %s() %s {\n", p.Name, recv)
	emitConstructorBody(b, p, g, "\t", "c", "v")
	fmt.Fprintf(b, "\treturn v\n")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "")
}

// emitConstructorBody writes the lines that invoke the constructor and assign
// the result to target. receiverVar is "c" or "s" depending on lifetime;
// target is the LHS where the provided value lands (e.g. "c.userSvc" or "v").
//
// To support all return shapes uniformly, the constructor call assigns to a
// local variable `v` (always `:=`) and then the local is copied to target.
// For singletons/scoped, target is a struct field; for transients, target is
// already `v` so the copy is elided.
func emitConstructorBody(b *bytes.Buffer, p Provider, g *Graph, indent, receiverVar, target string) {
	args := buildArgs(p, g, receiverVar)
	ctor := qualifiedFunc(p)
	call := fmt.Sprintf("%s(%s)", ctor, strings.Join(args, ", "))
	// localVar is the name of the local variable that receives the
	// constructor's first return value. For transients, target is already
	// "v" so we use it directly.
	localVar := "v"
	if target == "v" {
		localVar = "v"
	}
	assignToTarget := localVar != target
	switch {
	case p.Cleanup && p.ReturnsError:
		cleanupVar := "cleanup" + p.Name
		fmt.Fprintf(b, "%s%s, %s, err := %s\n", indent, localVar, cleanupVar, call)
		fmt.Fprintf(b, "%sif err != nil {\n", indent)
		fmt.Fprintf(b, "%s\tpanic(\"di: %s returned error: \" + err.Error())\n", indent, p.FuncName)
		fmt.Fprintf(b, "%s}\n", indent)
		fmt.Fprintf(b, "%s%s.cleanups = append(%s.cleanups, %s)\n", indent, receiverVar, receiverVar, cleanupWrap(cleanupVar, p.CleanupReturnsError))
		if assignToTarget {
			fmt.Fprintf(b, "%s%s = %s\n", indent, target, localVar)
		}
	case p.Cleanup:
		cleanupVar := "cleanup" + p.Name
		fmt.Fprintf(b, "%s%s, %s := %s\n", indent, localVar, cleanupVar, call)
		fmt.Fprintf(b, "%s%s.cleanups = append(%s.cleanups, %s)\n", indent, receiverVar, receiverVar, cleanupWrap(cleanupVar, p.CleanupReturnsError))
		if assignToTarget {
			fmt.Fprintf(b, "%s%s = %s\n", indent, target, localVar)
		}
	case p.ReturnsError:
		fmt.Fprintf(b, "%s%s, err := %s\n", indent, localVar, call)
		fmt.Fprintf(b, "%sif err != nil {\n", indent)
		fmt.Fprintf(b, "%s\tpanic(\"di: %s returned error: \" + err.Error())\n", indent, p.FuncName)
		fmt.Fprintf(b, "%s}\n", indent)
		if assignToTarget {
			fmt.Fprintf(b, "%s%s = %s\n", indent, target, localVar)
		}
	default:
		if assignToTarget {
			fmt.Fprintf(b, "%s%s := %s\n", indent, localVar, call)
			fmt.Fprintf(b, "%s%s = %s\n", indent, target, localVar)
		} else {
			fmt.Fprintf(b, "%s%s := %s\n", indent, target, call)
		}
	}
}

// cleanupWrap returns the expression to append to the cleanups slice. If the
// cleanup function is `func()`, wrap it to `func() error { fn(); return nil }`.
// If it's already `func() error`, use it directly.
func cleanupWrap(cleanupVar string, returnsError bool) string {
	if returnsError {
		return cleanupVar
	}
	return fmt.Sprintf("func() error { %s(); return nil }", cleanupVar)
}

// buildArgs returns the accessor-call argument list for a provider's deps.
func buildArgs(p Provider, g *Graph, receiverVar string) []string {
	args := make([]string, 0, len(p.Requires))
	for _, r := range p.Requires {
		key := r.Key()
		if isBuiltinRef(key) {
			if r.Name == "Context" || r.Key().String() == "context.Context" {
				args = append(args, "ctx")
			} else {
				args = append(args, "nil")
			}
			continue
		}
		rp, ok := g.providers[key]
		if !ok {
			// External dep: read from c.deps.<Field>.
			args = append(args, receiverVar+".deps."+depFieldName(r))
			continue
		}
		switch rp.Lifetime {
		case LifetimeSingleton:
			args = append(args, receiverVar+"."+rp.Name+"()")
		case LifetimeScoped:
			args = append(args, receiverVar+"."+rp.Name+"(ctx)")
		case LifetimeTransient:
			args = append(args, receiverVar+"."+rp.Name+"()")
		}
	}
	return args
}

// qualifiedFunc renders the constructor's fully qualified reference, e.g.
// `services.NewUserService`.
func qualifiedFunc(p Provider) string {
	if p.PkgName == "" {
		return p.FuncName
	}
	return p.PkgName + "." + p.FuncName
}

// qualifiedType renders a TypeRef for use in the generated file. The ctor's
// package path is supplied so same-package types (declared in the same
// package as the constructor, but referenced from the generated file in a
// different package) are prefixed with the ctor's package name.
func qualifiedType(t TypeRef, ctorPkgPath, ctorPkgName string) string {
	if t.PkgPath == "" {
		// Builtin (error, context.Context, or unresolved same-package type
		// from a file with no go.mod context). Expr is the source form.
		return t.Expr
	}
	// Different package: Expr already contains the selector.
	if t.PkgPath != ctorPkgPath {
		return t.Expr
	}
	// Same package as the constructor: qualify the bare name. The Expr is
	// a source-level form like "*UserService" or "[]Pool" — we insert the
	// package qualifier after any leading pointer/slice markers.
	return qualifySamePackage(t.Expr, ctorPkgName)
}

// qualifySamePackage inserts pkgName before the bare type identifier in expr.
// Handles leading pointer/slice/ellipsis markers.
func qualifySamePackage(expr, pkgName string) string {
	prefix := ""
	rest := expr
	for {
		switch {
		case strings.HasPrefix(rest, "*"):
			prefix += "*"
			rest = rest[1:]
		case strings.HasPrefix(rest, "[]"):
			prefix += "[]"
			rest = rest[2:]
		case strings.HasPrefix(rest, "..."):
			prefix += "..."
			rest = rest[3:]
		default:
			return prefix + pkgName + "." + rest
		}
	}
}

// lowerFirst returns s with its first byte lower-cased. Used to derive field
// names from provider names.
func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	r := []byte(s)
	if r[0] >= 'A' && r[0] <= 'Z' {
		r[0] += 'a' - 'A'
	}
	return string(r)
}

// importEntry is one row in the generated import block.
type importEntry struct {
	alias string
	path  string
}

// collectImports returns the sorted, de-duplicated imports the generated file
// needs: every provider's package plus every type's package plus externals.
func collectImports(order []Provider, externals []externalDep) []importEntry {
	seen := map[string]string{} // path → alias
	add := func(path, alias string) {
		if path == "" {
			return
		}
		if _, ok := seen[path]; ok {
			return
		}
		seen[path] = alias
	}
	for _, p := range order {
		add(p.PkgPath, p.PkgName)
		for _, r := range p.Requires {
			if r.PkgPath != "" && r.PkgPath != p.PkgPath {
				add(r.PkgPath, r.PkgName)
			}
		}
		if p.Provides.PkgPath != "" && p.Provides.PkgPath != p.PkgPath {
			add(p.Provides.PkgPath, p.Provides.PkgName)
		}
	}
	for _, e := range externals {
		add(e.Type.PkgPath, e.Type.PkgName)
	}
	out := make([]importEntry, 0, len(seen))
	for path, alias := range seen {
		out = append(out, importEntry{alias: alias, path: path})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].path < out[j].path })
	return out
}

// countByLifetime returns how many of order has the given lifetime.
func countByLifetime(order []Provider, lt Lifetime) int {
	n := 0
	for _, p := range order {
		if p.Lifetime == lt {
			n++
		}
	}
	return n
}

// needsContext reports whether the generated file must import "context".
// True when any provider is scoped (uses ctx) or any constructor requires a
// context.Context parameter.
func needsContext(order []Provider, externals []externalDep) bool {
	for _, p := range order {
		if p.Lifetime == LifetimeScoped {
			return true
		}
		for _, r := range p.Requires {
			if r.Key().String() == "context.Context" {
				return true
			}
		}
	}
	return false
}

// providersByLifetime returns the subset of order with the given lifetime.
func providersByLifetime(order []Provider, lt Lifetime) []Provider {
	var out []Provider
	for _, p := range order {
		if p.Lifetime == lt {
			out = append(out, p)
		}
	}
	return out
}
