// SPDX-License-Identifier: MIT
// Copyright (c) 2026 OgonFrameworks. All rights reserved.
//
// di/di.go: top-level entrypoints for the DI codegen pipeline. Used by
// `ogon build` to scan app/services, build the graph, and emit
// generated/di/di_gen.go in one call.
//
// Two equivalent API surfaces exist:
//   - High-level:   Scan(dir) → *Graph, (*Graph).Generate(outPath), (*Graph).Explain()
//   - Composable:   ScanDir(dir) → []Provider, NewGraph(provs, overrides),
//                   Generate(g, opts), Explain(g, w, opts)
//
// The high-level surface covers the spec's "tight scope" entrypoints; the
// composable surface is what `ogon build` and `ogon explain di` use directly
// when they need to thread through overrides, custom options, or stream output.

package di

import (
	"bytes"
	"fmt"
	"path/filepath"
)

// BuildOptions configures the end-to-end DI pipeline.
type BuildOptions struct {
	// ServicesDir is the directory to scan for constructors (default
	// "<projectRoot>/app/services").
	ServicesDir string
	// OutputPath is the generated file path (default
	// "<projectRoot>/generated/di/di_gen.go").
	OutputPath string
	// PackageName is the generated package name (default "di").
	PackageName string
	// Overrides are explicit ogon.Provide registrations (DI-007) that take
	// precedence over generated providers of the same type.
	Overrides []Provider
}

// Build scans, validates, and emits the typed container. Returns the rendered
// bytes (post-gofmt) so callers can snapshot or diff. On graph errors
// (missing/ambiguous/cycle/scope) Build returns an error and writes nothing.
func Build(opts BuildOptions) ([]byte, error) {
	if opts.ServicesDir == "" {
		return nil, fmt.Errorf("di: ServicesDir is empty")
	}
	if opts.OutputPath == "" {
		return nil, fmt.Errorf("di: OutputPath is empty")
	}
	providers, err := ScanDir(opts.ServicesDir)
	if err != nil {
		return nil, fmt.Errorf("di: scan %s: %w", opts.ServicesDir, err)
	}
	g, err := NewGraph(providers, opts.Overrides)
	if err != nil {
		return nil, fmt.Errorf("di: graph build: %w", err)
	}
	pkg := opts.PackageName
	if pkg == "" {
		pkg = "di"
	}
	return Generate(g, CodegenOptions{
		PackageName:   pkg,
		OutputPath:    opts.OutputPath,
		HeaderComment: "Code generated by ogon di. DO NOT EDIT.",
	})
}

// DefaultServicesDir returns "<root>/app/services".
func DefaultServicesDir(root string) string {
	return filepath.Join(root, "app", "services")
}

// DefaultOutputPath returns "<root>/generated/di/di_gen.go".
func DefaultOutputPath(root string) string {
	return filepath.Join(root, "generated", "di", "di_gen.go")
}

// Scan is the high-level entrypoint: walk dir for `NewX(deps) X` constructors,
// build the provider graph, and return it ready for Generate / Explain. Returns
// an error on scan failure, ambiguous providers (DI-017), cycles (DI-003), or
// scope violations (DI-023). Missing providers are surfaced via g.Missing()
// rather than failing the scan (DI-016).
//
// Equivalent to:
//
//	providers, err := ScanDir(dir)
//	if err != nil { return nil, err }
//	return NewGraph(providers, nil)
func Scan(dir string) (*Graph, error) {
	if dir == "" {
		return nil, fmt.Errorf("di: scan dir is empty")
	}
	providers, err := ScanDir(dir)
	if err != nil {
		return nil, fmt.Errorf("di: scan %s: %w", dir, err)
	}
	g, err := NewGraph(providers, nil)
	if err != nil {
		return nil, err
	}
	return g, nil
}

// Generate emits the typed container file at outPath using default codegen
// options (package "di", standard header). Returns an error if the graph is
// nil, the output path is empty, gofmt fails, or the file cannot be written.
// On success the generated file is byte-stable for identical inputs (DI-020)
// and contains no `map[string]any` runtime lookups (DI-018) and no reflection
// (DI-022).
//
// Equivalent to:
//
//	Generate(g, DefaultCodegenOptions(outPath))
func (g *Graph) Generate(outPath string) error {
	if _, err := Generate(g, DefaultCodegenOptions(outPath)); err != nil {
		return err
	}
	return nil
}

// Explain renders the graph as human-readable text (DI-014) using default
// explain options and returns it as a string. The output is stable for the same
// graph (DI-020). On a cycle or graph error the partial picture is rendered and
// the error is returned alongside; callers that want to surface the error in
// `ogon explain di` should use the streaming Explain(g, w, opts) form.
func (g *Graph) Explain() string {
	var buf bytes.Buffer
	_ = Explain(g, &buf, DefaultExplainOptions())
	return buf.String()
}
